#!/bin/sh
#
# See LICENSE file for license details.

BASEDIR="/etc/shsm"
BASENAME="$(basename "$0")"

[ -d "${BASEDIR}" ] || mkdir -p "${BASEDIR}"
cd "${BASEDIR}" || exit 1

usage() {
	printf "Usage: %s [-acdklrs] [service]\n" "${BASENAME}" >&2
	exit 0
}

runservice() {
	service="$1"
	dir="$2"
	cmd="$3"

	if [ "$(wc -c "${dir}/${service}" | awk '{print $1}')" -eq 0 ]; then
	[ $# -eq 0 ] && service="$0" || [ $# -gt 0 ] && service="$1" && shift 1
		"${service}" "${cmd}" > /dev/null 2>&1 &
	else
		"${dir}/${service}" "${cmd}" > /dev/null 2>&1 &
	fi
}

doservice() {
	cmd="$1"
	service="$2"

	if [ -z "${service}" ]; then
	services="$(find ./run -type l | awk -F "/" '{print $NF}')"
		for s in ${services};
		do
			runservice "$s" run "${cmd}"
			printf "%s: '%s' %s.\n" \
				"${BASENAME}" "$s" "${cmd}"
		done
	else
		if [ -x "./avail/${service}" ]; then
			runservice "${service}" avail "${cmd}"
			printf "%s: '%s' %s.\n" \
				"${BASENAME}" "${service}" "${cmd}"
		else
			printf "%s: '%s' is not available or executable.\n" \
				"${BASENAME}" "${service}" >&2
			exit 1
		fi
	fi
}

case "$1" in
	-a)
		if [ $# -gt 1 ] && [ -e "./avail/$2" ]; then
		[ -d ./run ] || mkdir -p ./run
			ln -sf "../avail/$2" "./run/$2"
			printf "%s: '%s' activated.\n" \
				"${BASENAME}" "$2"
		else
			[ -d ./run ] || exit 1
			find ./run -type l
		fi 
		;;	
	-c)
		[ -d ./avail ] || mkdir -p ./avail
		[ -d ./run ] || mkdir -p ./run
		;;
	-d)
		if [ $# -gt 1 ] && [ -e "./run/$2" ]; then
			rm -rf "./run/$2"
			printf "%s: '%s' deactivated.\n" \
				"${BASENAME}" "$2"
		else
			printf "%s: No service given or service is not marked as to run.\n" \
				"${BASENAME}" >&2
			exit 1
		fi
		;;
	-k|-s)
		doservice "$1" "$2"
		;;
	-l)
		find ./avail -type f
		;;
	-r)
		if [ $# -gt 1 ]; then
			set -x
			shsm -k "$2"
			shsm -s "$2"
		else
			printf "%s: please give a service name.\n" \
				"${BASENAME}" >&2
			exit 1
		fi
		;;
	*)
		usage
		;;
esac
