.TH svc 1
.SH NAME
svc
.SH SYNOPSIS
.B svc
.RB [\-acdkslr]
.RB [<service>] 
.SH DESCRIPTION
.B svc
is a simple service manager written in POSIX sh
.SH OPTIONS
.TP
.B \-a 
activate <service> - list all active services if no service is presented
.TP
.B \-c
create the basic directories for svc
.TP
.B \-d
deactivate <service>
.TP
.B \-k
kill <service> - if no option is presented, kill all services
.TP
.B \-s
start <service> - if no service is presented, run all actived services
.TP
.B \-l
list all available services
.TP
.B \-r
restart <service>
.TP
