#!/bin/sh

SERVICE="barebone"

# shellcheck source=/dev/null
[ -e "/etc/svc.d/default/$SERVICE" ] && . "/etc/svc.d/default/$SERVICE"

BIN="/usr/bin/$SERVICE"

PID=$(pidof -o %PPID "$BIN")

case $1 in
	-s)
		[ -z "$PID" ] && $BIN "$PARAMS";
		;;
	-k)
		[ -n "$PID" ] && kill -9 "$PID" > /dev/null 2>&1;
		;;
	*)
		echo "usage: $0 -s|-k"
		exit 1
esac

