#!/bin/sh

case $1 in
	-s)
		exec iwd -d
		;;
	-k)
  ps > ps_output
  PID="$(grep iwd ps_output | awk '{print $1}')"

  for n in "$PID"; do
    kill -9 $n
  done

  rm -r ps_output
		;;
	*)
		echo "usage: $0 -s|-k"
		exit 1
esac

