#!/bin/sh

case $1 in
	-s) 
    # Null the legacy hotplugger as the service will take over from here.
    printf '\n' 2>/dev/null > /proc/sys/kernel/hotplug
    exec mdevd -f /etc/mdevd.conf -O 4
		;;
	-k)
    ps > ps_output
    PID="$(grep mdevd ps_output | awk '{print $1}')"

    for n in $PID; do
      kill -9 $n
    done
    rm -rf ps_output
		;;
	*)
		echo "usage: $0 -s|-k"
		exit 1
esac

