#!/bin/sh

SERVICE="nscd"

BIN="/bin/$SERVICE"

PID=$(pidof -o %PPID $BIN)

case $1 in
	-s)
		if [ -z "$PID" ];
		then
			rm -f "/run/$SERVICE.pid"  > /dev/null 2>&1
			mkdir -p /run/nscd /var/db/nscd
			rm -f /run/nscd/* /var/db/nscd/*  > /dev/null 2>&1

			$BIN "$PARAMS" > /dev/null 2>&1;
		fi
		;;
	-k)
		if [ -n "$PID" ];
		then
			nscd -K  > /dev/null 2>&1
			rm -f "/run/$SERVICE.pid" > /dev/null 2>&1
		fi
		;;
	*)
		echo "usage: $0 -s|-k"
		exit 1
esac

