#!/bin/sh

case $1 in
	-s)
		exec sdhcp -f wlan0 1> /dev/null
		;;
	-k)
		ps > out
    PID="$(grep sdhcp out | awk '{print $1}')"
    kill -9 $PID
    rm -rf out
		;;
	*)
		echo "usage: $0 -s|-k"
		exit 1
esac

